### ISSUE TITLE
Only running at 0.5-1 FPS on a 1080TI 

### ISSUE THREAD

**Issue by MartinJensen37** [noxouille/rt-mrcnn#4]
Have you had problems with the algorithm running incredibly slow? Do you know if there are any ways to make the computations easier other than decreasing the image size? Thanks in advance!

**Comment by noxouille** [comment]
Hi, apparently other people also have been having this slow issue, which I am not sure what cause this.
Maybe the OS, or any programs running in the background is affecting this?
I haven't been able to test this, as I no longer have access to the exact resources I used 2 years ago.
Unless someone already invented a faster algorithm for similar purpose, i don't have any specific method in mind to improve the performance.

**Comment by MartinJensen37** [comment]
I updated the graphics drivers and reinstalled cuda 9.0 and now it runs at 5-6 fps! :+1:
