### ISSUE TITLE
run_webcam.py | Use CPU instead of GPU

### ISSUE THREAD

**Issue by pmk-ai** [noxouille/rt-mrcnn#6]
Hi, My model is trained on GPU but to run on webcam I am planning to use CPU. 
How may a modify this code to enable CPU instead of GPU?

**Comment by noxouille** [comment]
Hello, I haven't had the time to maintain this repo, but if I remember correctly, if you go and check the [config.py](https://github.com/noxouille/rt-mrcnn/blob/master/mrcnn/config.py) line 28, as long as the `GPU_COUNT = 1`, you're good to go!
But don't expect too much running the code on CPU, as it's already struggling to have a decent performance on GPU.
